### ISSUE TITLE
Error when running unittest. FAILED (failures=1, errors=3)

### ISSUE THREAD

**Issue by rachyrachyrach** [HandCash/handcash-connect-sdk-python#1]
I ran `python3 -m unittest`

Location of where I ran the test
`/Users/rachael/github/handcash-connect-sdk-python`

Received `FAILED (failures=1, errors=3)`

Below is the full output of the test. 

```
.EEF.E....
======================================================================
ERROR: test_get_encryption_keypair (handcash_connect_sdk.tests.integration.test_profile.TestProfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/api/handcash_connect_service.py", line 49, in _handle_http_request
    response.raise_for_status()
  File "/Users/rachael/github/handcash-connect-sdk-python/.venv/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://cloud.handcash.io/v1/connect/profile/encryptionKeypair

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/tests/integration/test_profile.py", line 34, in test_get_encryption_keypair
    keypair = self.profile.get_encryption_keypair()
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/profile.py", line 31, in get_encryption_keypair
    encryption_keypair = self._handcash_connect_service.get_encryption_keypair(public_key.to_hex())
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/api/handcash_connect_service.py", line 26, in get_encryption_keypair
    return self._handle_http_request(
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/api/handcash_connect_service.py", line 54, in _handle_http_request
    raise HandCashConnectApiError(exc.response.status_code, message=response['message'], info=response['info'])
handcash_connect_sdk.api.handcash_connect_api_error.HandCashConnectApiError: 401

======================================================================
ERROR: test_get_friends (handcash_connect_sdk.tests.integration.test_profile.TestProfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/api/handcash_connect_service.py", line 49, in _handle_http_request
    response.raise_for_status()
  File "/Users/rachael/github/handcash-connect-sdk-python/.venv/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://cloud.handcash.io/v1/connect/profile/friends

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/tests/integration/test_profile.py", line 25, in test_get_friends
    user_profiles = self.profile.get_friends()
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/profile.py", line 23, in get_friends
    user_profile in self._handcash_connect_service.get_user_friends()["items"]]
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/api/handcash_connect_service.py", line 30, in get_user_friends
    return self._handle_http_request(
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/api/handcash_connect_service.py", line 54, in _handle_http_request
    raise HandCashConnectApiError(exc.response.status_code, message=response['message'], info=response['info'])
handcash_connect_sdk.api.handcash_connect_api_error.HandCashConnectApiError: 401

======================================================================
ERROR: test_get_payment (handcash_connect_sdk.tests.integration.test_wallet.TestWallet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/api/handcash_connect_service.py", line 49, in _handle_http_request
    response.raise_for_status()
  File "/Users/rachael/github/handcash-connect-sdk-python/.venv/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://cloud.handcash.io/v1/connect/wallet/payment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/tests/integration/test_wallet.py", line 50, in test_get_payment
    payment_result = self.wallet.get_payment(transaction_id)
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/wallet.py", line 18, in get_payment
    return PaymentResult(**self._handcash_connect_service.get_payment(transaction_id))
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/api/handcash_connect_service.py", line 42, in get_payment
    return self._handle_http_request(
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/api/handcash_connect_service.py", line 54, in _handle_http_request
    raise HandCashConnectApiError(exc.response.status_code, message=response['message'], info=response['info'])
KeyError: 'info'

======================================================================
FAIL: test_get_permissions (handcash_connect_sdk.tests.integration.test_profile.TestProfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/tests/integration/test_profile.py", line 31, in test_get_permissions
    self.assertListEqual(expected, sorted(permissions))
AssertionError: Lists differ: ['DECRYPT', 'FRIENDS', 'PAY', 'USER_PRIVATE_PROFILE', 'USER_PUBLIC_PROFILE'] != ['PAY', 'SIGN_DATA', 'USER_PRIVATE_PROFILE', 'USER_PUBLIC_PROFILE']

First differing element 0:
'DECRYPT'
'PAY'

First list contains 1 additional elements.
First extra element 4:
'USER_PUBLIC_PROFILE'

- ['DECRYPT', 'FRIENDS', 'PAY', 'USER_PRIVATE_PROFILE', 'USER_PUBLIC_PROFILE']
?  ----------------------

+ ['PAY', 'SIGN_DATA', 'USER_PRIVATE_PROFILE', 'USER_PUBLIC_PROFILE']
?        +++++++++++++


----------------------------------------------------------------------
Ran 10 tests in 5.482s

FAILED (failures=1, errors=3)
```

**Comment by rachyrachyrach** [comment]
I did a `git pull` and ran the test again. This test only received 1 error.  

```
.....E....
======================================================================
ERROR: test_get_payment (handcash_connect_sdk.tests.integration.test_wallet.TestWallet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/api/handcash_connect_service.py", line 49, in _handle_http_request
    response.raise_for_status()
  File "/Users/rachael/github/handcash-connect-sdk-python/.venv/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://cloud.handcash.io/v1/connect/wallet/payment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/tests/integration/test_wallet.py", line 50, in test_get_payment
    payment_result = self.wallet.get_payment(transaction_id)
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/wallet.py", line 18, in get_payment
    return PaymentResult(**self._handcash_connect_service.get_payment(transaction_id))
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/api/handcash_connect_service.py", line 42, in get_payment
    return self._handle_http_request(
  File "/Users/rachael/github/handcash-connect-sdk-python/handcash_connect_sdk/api/handcash_connect_service.py", line 54, in _handle_http_request
    raise HandCashConnectApiError(exc.response.status_code, message=response['message'], info=response['info'])
KeyError: 'info'

----------------------------------------------------------------------
Ran 10 tests in 5.402s

FAILED (errors=1)
```

**Comment by rachyrachyrach** [comment]
Updated my requirements.txt file with the new recommendation from Rafa which fixed the issue.  We replaced the `handcash-connect-sdk==0.2.0` with
 `git+https://github.com/HandCash/handcash-connect-sdk-python.git@main#egg=handcash-connect-sdk` which worked and we can now test out our wallets.  Receiving and sending payment works.
